### ISSUE TITLE
Captures Strange Articfacts From the Top of the pdf

### ISSUE THREAD

**Issue by arham-saif** [ripeta/general#10]
Below are pictures that seem to show how our current plugins capture strange artifacts from the pdf fle itself. In this example, the artifact it captures when uploaded shows up as the name of the title of the article.

![captures strange artifacts from the top of the pdf 1 2](https://user-images.githubusercontent.com/43044812/45383926-2d259f00-b5d2-11e8-8780-e11929a04987.jpg)
![captures strange artifacts from the top of the pdf 2 2](https://user-images.githubusercontent.com/43044812/45383939-344cad00-b5d2-11e8-86f6-b462a7f9fabd.png)

**Comment by ejcramer** [comment]
This is a good observation, the article_title plugin is doing what we told it to do.  Because we are not submitting a title in the frontend, we try to get it with the article_title plugin.  It does the following:

1.  Uses the title submitted if available. Not available on front-end, only ingest. If none:
2. Uses the PDF info metadata title.  Not always present or good, but takes it.
3. Uses the first line of the text extracted from the PDF if is a stand-alone line.  Not always good.
4. Uses the filename.  Not great, but at least might be recognizable by uploader.

We can keep discussing this, but it's the best we've come up with so far.  I'll close for now.
